-- ============================================================
-- Base Framework Schema
-- Generated by forge.php — extend this for your project.
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ─── auth — User Credentials ──────────────────────────────
DROP TABLE IF EXISTS `auth`;
CREATE TABLE `auth` (
  `id`         int          NOT NULL AUTO_INCREMENT,
  `username`   varchar(32)  NOT NULL,
  `password`   varchar(256) NOT NULL,
  `email`      varchar(256) NOT NULL,
  `phone`      varchar(16)  NOT NULL DEFAULT '',
  `active`     tinyint(1)   NOT NULL DEFAULT 1,
  `blocked`    tinyint(1)   NOT NULL DEFAULT 0,
  `sec_email`  varchar(256)          DEFAULT NULL,
  `created_at` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_username` (`username`),
  UNIQUE KEY `uq_email`    (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ─── users — Extended Profile Data ───────────────────────
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id`         int           NOT NULL,
  `bio`        longtext,
  `avatar`     varchar(1024)          DEFAULT NULL,
  `firstname`  varchar(128)  NOT NULL DEFAULT '',
  `lastname`   varchar(128)  NOT NULL DEFAULT '',
  `dob`        date                   DEFAULT NULL,
  `instagram`  varchar(1024)          DEFAULT NULL,
  `twitter`    varchar(1024)          DEFAULT NULL,
  `facebook`   varchar(1024)          DEFAULT NULL,
  `created_at` datetime      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `fk_users_auth` (`id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`id`) REFERENCES `auth` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ─── session — Token Authentication ──────────────────────
DROP TABLE IF EXISTS `session`;
CREATE TABLE `session` (
  `id`          int          NOT NULL AUTO_INCREMENT,
  `uid`         int          NOT NULL,
  `token`       varchar(64)  NOT NULL,
  `login_time`  datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip`          varchar(45)           DEFAULT NULL,
  `user_agent`  text                  DEFAULT NULL,
  `active`      tinyint(1)   NOT NULL DEFAULT 1,
  `fingerprint` varchar(256)          DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_token` (`token`),
  KEY `fk_session_auth` (`uid`),
  CONSTRAINT `session_ibfk_1` FOREIGN KEY (`uid`) REFERENCES `auth` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ─── posts — Content Table ────────────────────────────────
DROP TABLE IF EXISTS `posts`;
CREATE TABLE `posts` (
  `id`            int          NOT NULL AUTO_INCREMENT,
  `title`         varchar(512) NOT NULL,
  `subtitle`      varchar(512)          DEFAULT NULL,
  `content`       longtext              DEFAULT NULL,
  `category`      varchar(128)          DEFAULT NULL,
  `image`         varchar(1024)         DEFAULT NULL,
  `pdf`           varchar(1024)         DEFAULT NULL,
  `like_count`    int          NOT NULL DEFAULT 0,
  `draft`         tinyint(1)   NOT NULL DEFAULT 0,
  `alias`         varchar(512)          DEFAULT NULL,
  `owner`         varchar(256)          DEFAULT NULL,  -- email of the author
  `uploaded_time` datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`),
  KEY `idx_alias`    (`alias`(191)),
  KEY `idx_owner`    (`owner`(128))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
